### ISSUE TITLE
bug(iflow): Cookie auth method fails for accounts without prior OAuth Email Login

### ISSUE THREAD

**Issue by MasuRii** [Mirrowel/LLM-API-Key-Proxy#117]
## Description

The iFlow cookie authentication method doesn't work for new accounts that haven't previously authenticated using the "OAuth Email Login" method.

## Steps to Reproduce

1. Set up a new iFlow account
2. Attempt to use the "Cookie" authentication method directly (without ever using OAuth Email Login)
3. Observe the error

## Expected Behavior

Cookie authentication should work independently without requiring a prior OAuth Email Login.

## Actual Behavior

The following error is displayed:

```
Validating cookie...
╭─────────────────────────────────────────────────────── Error ────────────────────────────────────────────────────────╮
│ Credential setup failed: 'NoneType' object has no attribute 'get'                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Press Enter to return to main menu...
```

## Workaround

For new accounts, the following sequence works:

1. **First**: Complete the "OAuth Email Login" method at least once
2. **Then**: Switch to the "Cookie" authentication method

After performing OAuth Email Login once, the Cookie method will work correctly.

## Environment

- Provider: iFlow
- Component: Cookie authentication

**Comment by MasuRii** [comment]
Check the dev branch, that's the one that I've been using.

**Comment by MasuRii** [comment]
Check the dev branch, that's the one that I've been using. @mirrobot-agent
